### ISSUE TITLE
Cannot Read Property Length

### ISSUE THREAD

**Issue by okcjosh** [TwilioDevEd/notifier-node#8]
Aside from not being able to requisition a new Notification service at twilio I decided to try to use an existing SMS Messaging app and input the SID from that app into .env. Upon following the instructions exactly, NPM throws this error:

TypeError: /Users/verbal/notifier-node/views/layout.pug:23
   21|             span.icon-bar
   22|     .container

> 23|       for data in flash
>    24|         .alert.alert-dismissible.alert-success
>    25|           button.close(type='button', data-dismiss='alert') ×
>    26|           span= data.message

Cannot read property 'length' of undefined
   at eval (eval at wrap (/Users/verbal/notifier-node/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:51:31)
   at eval (eval at wrap (/Users/verbal/notifier-node/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:82:4)
   at template (eval at wrap (/Users/verbal/notifier-node/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:116:155)
   at Object.exports.renderFile (/Users/verbal/notifier-node/node_modules/pug/lib/index.js:410:38)
   at Object.exports.renderFile (/Users/verbal/notifier-node/node_modules/pug/lib/index.js:400:21)
   at View.exports.__express [as engine](/Users/verbal/notifier-node/node_modules/pug/lib/index.js:447:11)
   at View.render (/Users/verbal/notifier-node/node_modules/express/lib/view.js:126:8)
   at tryRender (/Users/verbal/notifier-node/node_modules/express/lib/application.js:639:10)
   at EventEmitter.render (/Users/verbal/notifier-node/node_modules/express/lib/application.js:591:3)
   at ServerResponse.render (/Users/verbal/notifier-node/node_modules/express/lib/response.js:960:7)

**Comment by dprothero** [comment]
Thanks okcjosh. Currently Notify is still in developer preview. You can request access here:
https://www.twilio.com/console/form/notify-access
